export const FETCH_DISCOVER_PHOTOS_API = "FETCH_DISCOVER_PHOTOS_API";
export const FETCH_DISCOVER_PHOTOS_API_FAILURE = "FETCH_DISCOVER_PHOTOS_API_FAILURE";
export const FETCH_DISCOVER_PHOTOS_API_SUCCESS = "FETCH_DISCOVER_PHOTOS_API_SUCCESS";

export default {
    FETCH_DISCOVER_PHOTOS_API,
    FETCH_DISCOVER_PHOTOS_API_FAILURE,
    FETCH_DISCOVER_PHOTOS_API_SUCCESS
}


